---
- name: Provision ec2 instance
  ec2:
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    region: "{{ ec2_region }}"
    zone: "{{ ec2_az }}"
    group_id: "{{ sg_id }}"
    vpc_subnet_id: "{{ private_subnet_id }}"
    wait: true
    count: 1
    state: "{{ state }}"
    assign_public_ip: yes
    termination_protection: "{{ termination_protection }}"
    volumes:
      - device_name: "{{ ec2_device_name }}"
        volume_type: "{{ ec2_volume_type }}"
        volume_size: "{{ ec2_root_volume_size }}"
        delete_on_termination: "{{ ec2_volume_delete_on_termination }}"
    instance_tags:
      Name: "{{ item.name }}"
      Type: "{{ item.type }}"
      Group: "{{ item.group }}"
  register: ec2
  with_items: "{{ ec2_instance_details }}"

#- debug:
#    msg: "{{ ec2.instances }}"
